"""Content identity shared by runtime, Tint CLI, precompiled tables and seeds."""

import argparse
import hashlib
import struct
from pathlib import Path

SOURCE_SUFFIXES = {".c", ".cc", ".cpp", ".h", ".hh", ".hpp", ".inc", ".def"}
LOCAL_INPUTS = (
    "drivers/webgpu/cache_identity.py",
    "drivers/webgpu/target_profile.json",
    "drivers/webgpu/rendering_device_driver_webgpu.cpp",
    "drivers/webgpu/rendering_device_driver_webgpu.h",
    "drivers/webgpu/spirv_preprocess.cpp",
    "drivers/webgpu/spirv_preprocess.h",
    "drivers/webgpu/sampled_texture_usage.h",
    "drivers/webgpu/tint_wrapper.cpp",
    "drivers/webgpu/tint_wrapper.h",
    "drivers/webgpu/tint_cli/main.cpp",
    "drivers/webgpu/tint_cli/build.sh",
    "drivers/webgpu/wgsl_precompile.py",
    "drivers/webgpu/SCsub",
    "editor/shader/shader_baker/shader_baker_export_plugin_platform_webgpu.cpp",
)
VENDOR_ROOTS = ("thirdparty/tint", "thirdparty/spirv-tools", "thirdparty/spirv-headers")


def vendor_inputs(repo, roots=VENDOR_ROOTS):
    return sorted(
        path.relative_to(repo).as_posix()
        for root in roots
        for path in (repo / root).rglob("*")
        if path.is_file() and path.suffix in SOURCE_SUFFIXES
    )


def source_inputs(repo):
    repo = Path(repo)
    driver_sources = [
        path.relative_to(repo).as_posix()
        for path in (repo / "drivers/webgpu").glob("*")
        if path.is_file() and path.suffix in SOURCE_SUFFIXES and ".gen." not in path.name
    ]
    shims = [path.relative_to(repo).as_posix() for path in (repo / "drivers/webgpu/tint_cli/core").rglob("*.h")]
    return sorted(set([*LOCAL_INPUTS, *driver_sources, *shims, *vendor_inputs(repo)]))


def fingerprint(repo, inputs=None):
    repo = Path(repo)
    digest = hashlib.sha256(b"godot-webgpu-translator-profile-v1\0")
    for name in source_inputs(repo) if inputs is None else sorted(inputs):
        encoded, contents = name.encode("utf-8"), (repo / name).read_bytes()
        digest.update(struct.pack("<I", len(encoded)))
        digest.update(encoded)
        digest.update(struct.pack("<Q", len(contents)))
        digest.update(contents)
    return digest.hexdigest()


def write_if_changed(path, text):
    path = Path(path)
    if path.exists() and path.read_text() == text:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def write_header(repo, output):
    value = fingerprint(repo)
    byte_values = ", ".join(f"0x{value[i : i + 2]}" for i in range(0, len(value), 2))
    write_if_changed(
        output,
        "// Generated by cache_identity.py; do not edit.\n#pragma once\n#include <cstdint>\n"
        f'static constexpr char WEBGPU_TRANSLATOR_FINGERPRINT[] = "{value}";\n'
        f"static constexpr uint8_t WEBGPU_TRANSLATOR_FINGERPRINT_BYTES[32] = {{ {byte_values} }};\n",
    )
    return value


def write_build_stamps(repo, directory):
    # The CLI's standalone build does not use SCons dependency scanning.
    # Component stamps prevent an edited vendored header from being silently
    # paired with a newly advertised identity and an old object file.
    repo, directory = Path(repo), Path(directory)
    build_inputs = ["drivers/webgpu/tint_cli/build.sh", "drivers/webgpu/cache_identity.py"]
    tools = vendor_inputs(repo, ("thirdparty/spirv-tools", "thirdparty/spirv-headers"))
    tint = vendor_inputs(repo, ("thirdparty/tint",))
    for component, inputs in (
        ("spirv_tools", [*build_inputs, *tools]),
        ("tint", [*build_inputs, *tools, *tint]),
        ("cli", source_inputs(repo)),
    ):
        write_if_changed(directory / f"{component}.inputs", fingerprint(repo, inputs) + "\n")


def build_header(target, source, env):
    write_header(Path(str(env.Dir("#"))), str(target[0]))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--header", type=Path)
    parser.add_argument("--build-stamps", type=Path)
    args = parser.parse_args()
    if args.header:
        value = write_header(args.repo, args.header)
    else:
        value = fingerprint(args.repo)
    if args.build_stamps:
        write_build_stamps(args.repo, args.build_stamps)
    print(value)
